symbol: ETH
train_years: 4
eval_days: 60
buy_threshold: 1.01  # y=1 if mean return over forecast_window > 1%, else 0
features:
  - RawClose
  - LogReturn
  - Sign
  - Volume
  - RPR
  - RSI
  - StochasticOscillator
  - MACD
  - EMA5
  - EMA20
  - BollingerBandHigh
  - BollingerBandLow
  - RawCloseBTC
  - LogReturnBTC
  - SignBTC
  - GoogleTrends
hyperparameters:
  look_back_window: 14
  forecast_window: 3
  layers: 8
  units: 256
  dropout_rate: 0.1